// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_hope_you_didnt_burn_anything_expensive = "CgkIroyrwZUYEAIQHA"; // <GPGSID>
        public const string achievement_mind_if_i_take_your_blood = "CgkIroyrwZUYEAIQJw"; // <GPGSID>
        public const string achievement_first_steps = "CgkIroyrwZUYEAIQAA"; // <GPGSID>
        public const string achievement_annihilation = "CgkIroyrwZUYEAIQDQ"; // <GPGSID>
        public const string achievement_your_princess_is_in_another_castle = "CgkIroyrwZUYEAIQBA"; // <GPGSID>
        public const string achievement_go_deeper = "CgkIroyrwZUYEAIQAw"; // <GPGSID>
        public const string achievement_devil_slayer = "CgkIroyrwZUYEAIQDg"; // <GPGSID>
        public const string achievement_hunter = "CgkIroyrwZUYEAIQDA"; // <GPGSID>
        public const string achievement_well_that_a_lot_of_crispy_chicken = "CgkIroyrwZUYEAIQGw"; // <GPGSID>
        public const string achievement_did_you_cheat = "CgkIroyrwZUYEAIQCA"; // <GPGSID>
        public const string achievement_improvements_in_progress = "CgkIroyrwZUYEAIQIQ"; // <GPGSID>
        public const string achievement_git_gud = "CgkIroyrwZUYEAIQCw"; // <GPGSID>
        public const string achievement_walking_simulator = "CgkIroyrwZUYEAIQBQ"; // <GPGSID>
        public const string achievement_burn_these_heretics = "CgkIroyrwZUYEAIQKQ"; // <GPGSID>
        public const string achievement_hope_you_didnt_kill_any_friend_in_this_frenzy = "CgkIroyrwZUYEAIQFw"; // <GPGSID>
        public const string achievement_learning = "CgkIroyrwZUYEAIQCg"; // <GPGSID>
        public const string achievement_its_a_trap = "CgkIroyrwZUYEAIQEA"; // <GPGSID>
        public const string achievement_2_birds_with_1_spell = "CgkIroyrwZUYEAIQKA"; // <GPGSID>
        public const string achievement_the_coward_way = "CgkIroyrwZUYEAIQCQ"; // <GPGSID>
        public const string achievement_5_points_for_gryffindor = "CgkIroyrwZUYEAIQHg"; // <GPGSID>
        public const string achievement_on_the_edge = "CgkIroyrwZUYEAIQEw"; // <GPGSID>
        public const string achievement_its_big_brain_time = "CgkIroyrwZUYEAIQBw"; // <GPGSID>
        public const string achievement_pew_pew_bang_bang = "CgkIroyrwZUYEAIQJA"; // <GPGSID>
        public const string achievement_shut_up_and_take_my_money = "CgkIroyrwZUYEAIQIg"; // <GPGSID>
        public const string achievement_god_slayer = "CgkIroyrwZUYEAIQDw"; // <GPGSID>
        public const string achievement_sharpness_iv = "CgkIroyrwZUYEAIQIw"; // <GPGSID>
        public const string achievement_full_counter = "CgkIroyrwZUYEAIQFg"; // <GPGSID>
        public const string achievement_bloodbath_incoming = "CgkIroyrwZUYEAIQJg"; // <GPGSID>
        public const string achievement_sogeking = "CgkIroyrwZUYEAIQKw"; // <GPGSID>
        public const string achievement_energy_saving = "CgkIroyrwZUYEAIQEg"; // <GPGSID>
        public const string achievement_collateral_damage = "CgkIroyrwZUYEAIQKg"; // <GPGSID>
        public const string achievement_money_money_money = "CgkIroyrwZUYEAIQFQ"; // <GPGSID>
        public const string achievement_youre_like_billy_the_kid__but_uglier = "CgkIroyrwZUYEAIQGg"; // <GPGSID>
        public const string achievement_the_good_the_bad_and_the_abyss = "CgkIroyrwZUYEAIQHw"; // <GPGSID>
        public const string achievement_exploooooosion = "CgkIroyrwZUYEAIQJQ"; // <GPGSID>
        public const string achievement_i_shot_u_ded = "CgkIroyrwZUYEAIQGQ"; // <GPGSID>
        public const string achievement_pff_even_i_can_do_that = "CgkIroyrwZUYEAIQBg"; // <GPGSID>
        public const string achievement_war_machine = "CgkIroyrwZUYEAIQIA"; // <GPGSID>
        public const string achievement_they_were_so_cute_now_they_are_dead = "CgkIroyrwZUYEAIQGA"; // <GPGSID>
        public const string achievement_oops_i_did_it_again = "CgkIroyrwZUYEAIQEQ"; // <GPGSID>
        public const string achievement_pocket_savings = "CgkIroyrwZUYEAIQFA"; // <GPGSID>
        public const string achievement_gotta_go_fast = "CgkIroyrwZUYEAIQHQ"; // <GPGSID>

}

